Fix pillow version check on macOS.
dbe9cb89 introduced a version check using PIL.__version__ assuming that
that attribute is a int-tuple whereas it's really just a string, leading
to a type error on even the most basic usage on macOS:

    >>> pyscreeze.screenshot()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/home/notebooks/pyscreeze/pyscreeze/__init__.py", line 527, in _screenshot_osx
        if tuple(PIL__version__) < (6, 2, 1):
    TypeError: '<' not supported between instances of 'str' and 'int'

Convert the offending version string to an int-tuple.